function sequenceIDs = step_RigidTranslate(sequenceIDs, GCO)
    %Copyright 2021 LabMonti.  Written by Nathan Bamberger.  This work is 
    %licensed under the Creative Commons Attribution-NonCommercial 4.0 
    %International License. To view a copy of this license, visit 
    %http://creativecommons.org/licenses/by-nc/4.0/.  
    %
    %Function Description: Generate a trial MCMC step by trying to move
    %the entire sequence left or right rigidly by one node.
    %
    %~~~INPUTS~~~:
    %
    %sequenceIDs: vector listing the node ID# for each node in the
    %   node-sequence
    %
    %GCO: GridCorrelationObject containing all the node information for the
    %   dataset that the MCMC is being run on 
    %
    %######################################################################
    %
    %~~~OUTPUTS~~~:
    %  
    %sequenceIDs: vector listing the node ID#s for the new sequence
    %   generated by the trial step; will be NaN if the trial step was
    %   automatically rejected because it would have fallen off the
    %   existing nodes
    
    
    %With 50% probability, try moving right
    if rand() > 0.5
        
        %If ANY of the nodes cannot be moved right, return NaN (will be
        %interpreted as an instant reject) (column 4 for eastern neighbors)
        if any(GCO.MissingNeighbors(sequenceIDs,4))
            sequenceIDs = NaN;
        else
            sequenceIDs = GCO.HorizontalNeighbors(sequenceIDs,2);
        end
        
    %With 50% probability, try moving left
    else
        
        %If ANY of the nodes cannot be moved left, return NaN (will be
        %interpreted as an instant reject) (column 3 for western neighbors)
        if any(GCO.MissingNeighbors(sequenceIDs,3))
            sequenceIDs = NaN;
        else
            sequenceIDs = GCO.HorizontalNeighbors(sequenceIDs,1);
        end        
    end

end