function sequenceIDs = step_RigidShift(sequenceIDs, GCO)
    %Copyright 2021 LabMonti.  Written by Nathan Bamberger.  This work is 
    %licensed under the Creative Commons Attribution-NonCommercial 4.0 
    %International License. To view a copy of this license, visit 
    %http://creativecommons.org/licenses/by-nc/4.0/.  
    %
    %Function Description: Generate a trial MCMC step by trying to move
    %the entire node sequence up or down rigidly by one node.
    %
    %~~~INPUTS~~~:
    %
    %sequenceIDs: vector listing the node ID# for each node in the
    %   node-sequence
    %
    %GCO: GridCorrelationObject containing all the node information for the
    %   dataset that the MCMC is being run on 
    %
    %######################################################################
    %
    %~~~OUTPUTS~~~:
    %  
    %sequenceIDs: vector listing the node ID#s for the new sequence
    %   generated by the trial step; will be NaN if the trial step was
    %   automatically rejected because it would have fallen off the
    %   existing nodes
    
    
    %With 50% probability, try moving up
    if rand() > 0.5
        
        %If ANY of the nodes cannot be moved up, return NaN (will be
        %interpreted as an instant reject) (column 2 for northern
        %neighbors)
        if any(GCO.MissingNeighbors(sequenceIDs,2))
            sequenceIDs = NaN;
        else
            sequenceIDs = GCO.VerticalNeighbors(sequenceIDs,2);
        end
        
    %With 50% probability, try moving down
    else
        
        %If ANY of the nodes cannot be moved down, return NaN (will be
        %interpreted as an instant reject) (column 1 for southern
        %neighbors)
        if any(GCO.MissingNeighbors(sequenceIDs,1))
            sequenceIDs = NaN;
        else
            sequenceIDs = GCO.VerticalNeighbors(sequenceIDs,1);
        end        
    end

end